name: Build and Code Checkstyle

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build and Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build backend
        run: ./gradlew build

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

  frontend:
    name: Frontend Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java for Frontend
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build frontend
        run: mvn clean install
        working-directory: frontend

      - name: Run Checkstyle for Frontend
        run: mvn checkstyle:check
        working-directory: frontend
