name: Build and Code Checkstyle

on:
  push:
    branches:
      - main
      - dev
      - CICD
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build and Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build backend with Maven
        run: mvn clean install

      - name: Run Checkstyle
        run: mvn checkstyle:check

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: src/frontend

      - name: Build frontend
        run: npm run build
        working-directory: src/frontend

